development:
  secret_key_base: e211f135d2589a711793e1dae71c8e5dcee03635e941ad50a2f8cfa6a8f3ecfef77322f8d6d9ddfa58fd445d204346365e5d471dd58c0211a2d5f9264d241326

test:
  secret_key_base: abd04f436db8cba7a019d6efabcdb850018d65b99a308e1982bca7da498a8803879f8a3883e1bc04f94c9f0c36f7b8a847335345089b7237fe4b0d8bd321cf53

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
